### PR TITLE
NOJIRA Remove prebuilt files

### PR DESCRIPTION
**Pull request by JockeTF**
Let's just not have these around at all in our branch.

### CODE REVIEW

**Review by PBJ12295 — APPROVED** [review]

**Comment by OskarHulter** [comment]
Are all 3000 of these files generated during the buildstep? If that is the case then the change makes sense :)

**Comment by joso9001** [comment]
> Are all 3000 of these files generated during the buildstep? If that is the case then the change makes sense :)

Yes, though not in the exact same location. There's a shared vendor directory, for example.

**Comment by OskarHulter** [comment]
I approve of the changes but I think my personal account hasn't been added on here yet so I can't "make it official" just yet. Would you mind adding me (or correcting me..) @JockeTF? :)

**Review by OskarHulter — APPROVED** [review]

**Comment by JockeTF** [comment]
This was a bad idea!

**Pull request closed without merging**
